import type { MaestroConfig } from "../types/maestro.types";
import { SHAREPOINT_CONFIG } from "./sharepoint.config";

export const maestrosConfig: Record<string, MaestroConfig> = {
  autoridades: {
    key: "autoridades",
    titulo: "Autoridades",
    descripcion: "Administración de autoridades visitantes.",
    listaId: SHAREPOINT_CONFIG.lists.autoridades,
    titleField: "Nombres",
    fields: [
      {
        key: "TipoDocIdentidad",
        label: "Tipo de documento",
        type: "lookup",
        required: true,
        visibleInTable: true,
        catalogoKey: "tiposDocumento",
      },
      {
        key: "NroDocumentoIdentidad",
        label: "Nro. documento",
        type: "text",
        required: true,
        visibleInTable: true,
        maxLength: 8,
      },
      {
        key: "Nombres",
        label: "Nombres",
        type: "text",
        required: true,
        visibleInTable: true,
      },
      {
        key: "Apellidos",
        label: "Apellidos",
        type: "text",
        required: true,
        visibleInTable: true,
      },
      {
        key: "Correo",
        label: "Correo",
        type: "email",
        visibleInTable: true,
      },
      {
        key: "Cargo",
        label: "Cargo",
        type: "lookup",
        required: true,
        visibleInTable: true,
        catalogoKey: "cargos",
      },
      {
        key: "TipoEntidad",
        label: "Tipo de entidad",
        type: "lookup",
        required: true,
        visibleInTable: true,
        catalogoKey: "tiposEntidad",
      },
      {
        key: "Activo",
        label: "Activo",
        type: "boolean",
        visibleInTable: true,
      },
    ],
  },

  personal: {
    key: "personal",
    titulo: "Personal PRONIED",
    descripcion: "Administración del personal PRONIED.",
    listaId: "UZ_Personal",
    titleField: "Nombres",
    fields: [
      {
        key: "IdTipoDocIdentidad",
        label: "Tipo de documento",
        type: "lookup",
        required: true,
        visibleInTable: true,
        catalogoKey: "tiposDocumento",
      },
      {
        key: "NroDocumentoIdentidad",
        label: "Nro. documento",
        type: "text",
        required: true,
        visibleInTable: true,
        maxLength: 8,
      },
      {
        key: "Nombres",
        label: "Nombres",
        type: "text",
        required: true,
        visibleInTable: true,
      },
      {
        key: "Apellidos",
        label: "Apellidos",
        type: "text",
        required: true,
        visibleInTable: true,
      },
      {
        key: "IdUnidadZonal",
        label: "Unidad Zonal",
        type: "lookup",
        required: true,
        visibleInTable: true,
        catalogoKey: "unidadesZonales",
      },
      {
        key: "IdCargo",
        label: "Cargo",
        type: "lookup",
        required: true,
        visibleInTable: true,
        catalogoKey: "cargos",
      },
      {
        key: "IdModalidadContratacion",
        label: "Modalidad",
        type: "lookup",
        required: true,
        visibleInTable: true,
        catalogoKey: "modalidadContratacion",
      },
      {
        key: "MontoRemuneracion",
        label: "Remuneración",
        type: "number",
        required: true,
        visibleInTable: true,
      },
      {
        key: "CorreoInstitucional",
        label: "Correo Institucional",
        type: "email",
        visibleInTable: true,
      },
      {
        key: "NroCelular",
        label: "Celular",
        type: "text",
        visibleInTable: true,
      },
      {
        key: "Activo",
        label: "Activo",
        type: "boolean",
        visibleInTable: true,
      },
    ],
  },
  
};