import type { MaestroConfig } from "../types/maestro.types";

export const maestrosConfig: Record<string, MaestroConfig> = {
  autoridades: {
    key: "autoridades",
    titulo: "Autoridades",
    descripcion: "Administración de autoridades visitantes.",
    listaSharePoint: "UZ_Autoridad",
    titleField: "Nombres",
    fields: [
      {
        key: "TipoDocIdentidad",
        label: "Tipo de documento",
        type: "lookup",
        required: true,
        visibleInTable: true,
        lookupList: "UZ_TipoDocumentoIdentidad",
        lookupTextField: "field_1",
      },
      {
        key: "NroDocumentoIdentidad",
        label: "Nro. documento",
        type: "text",
        required: true,
        visibleInTable: true,
        maxLength: 8,
      },
      {
        key: "Nombres",
        label: "Nombres",
        type: "text",
        required: true,
        visibleInTable: true,
      },
      {
        key: "Apellidos",
        label: "Apellidos",
        type: "text",
        required: true,
        visibleInTable: true,
      },
      {
        key: "Correo",
        label: "Correo",
        type: "email",
        required: false,
        visibleInTable: true,
      },
      {
        key: "Cargo",
        label: "Cargo",
        type: "lookup",
        required: true,
        visibleInTable: true,
        lookupList: "UZ_Cargo",
        lookupTextField: "field_1",
      },
      {
        key: "TipoEntidad",
        label: "Tipo de entidad",
        type: "lookup",
        required: true,
        visibleInTable: true,
        lookupList: "UZ_TipoEntidad",
        lookupTextField: "field_2",
      },
      {
        key: "Activo",
        label: "Activo",
        type: "boolean",
        required: false,
        visibleInTable: true,
      },
    ],
  },

  personal: {
    key: "personal",
    titulo: "Personal PRONIED",
    descripcion: "Administración del personal PRONIED.",
    listaSharePoint: "UZ_Personal",
    titleField: "Nombres",
    fields: [
      {
        key: "TipoDocIdentidad",
        label: "Tipo de documento",
        type: "lookup",
        required: true,
        visibleInTable: true,
        lookupList: "UZ_TipoDocumentoIdentidad",
        lookupTextField: "Descripcion",
      },
      {
        key: "NroDocumentoIdentidad",
        label: "Nro. documento",
        type: "text",
        required: true,
        visibleInTable: true,
        maxLength: 8,
      },
      {
        key: "Nombres",
        label: "Nombres",
        type: "text",
        required: true,
        visibleInTable: true,
      },
      {
        key: "Apellidos",
        label: "Apellidos",
        type: "text",
        required: true,
        visibleInTable: true,
      },
      {
        key: "UnidadZonal",
        label: "Unidad Zonal",
        type: "lookup",
        required: true,
        visibleInTable: true,
        lookupList: "UZ_UnidadZonal",
        lookupTextField: "Descripcion",
      },
      {
        key: "Cargo",
        label: "Cargo",
        type: "lookup",
        required: true,
        visibleInTable: true,
        lookupList: "UZ_Cargo",
        lookupTextField: "Descripcion",
      },
      {
        key: "Correo",
        label: "Correo",
        type: "email",
        required: false,
        visibleInTable: true,
      },
      {
        key: "Activo",
        label: "Activo",
        type: "boolean",
        required: false,
        visibleInTable: true,
      },
    ],
  },

  entidades: {
    key: "entidades",
    titulo: "Entidades",
    descripcion: "Administración de entidades.",
    listaSharePoint: "UZ_Entidad",
    titleField: "Descripcion",
    fields: [
      {
        key: "TipoEntidad",
        label: "Tipo de entidad",
        type: "lookup",
        required: true,
        visibleInTable: true,
        lookupList: "UZ_TipoEntidad",
        lookupTextField: "Descripcion",
      },
      {
        key: "Descripcion",
        label: "Entidad",
        type: "text",
        required: true,
        visibleInTable: true,
      },
      {
        key: "Activo",
        label: "Activo",
        type: "boolean",
        visibleInTable: true,
      },
    ],
  },
};