import type { MaestroConfig } from "../types/maestro.types";
import { SHAREPOINT_CONFIG } from "./sharepoint.config";

export const maestrosConfig: Record<string, MaestroConfig> = {
  autoridades: {
    key: "autoridades",
    titulo: "Autoridades",
    descripcion: "Administración de autoridades visitantes.",
    listaId: SHAREPOINT_CONFIG.lists.autoridades,
    titleField: "Nombres",
    fields: [
      {
        key: "IdTipoDocIdentidad",
        label: "Tipo de documento",
        type: "lookup",
        required: true,
        visibleInTable: true,
        catalogoKey: "tiposDocumento",
      },
      {
        key: "NroDocumentoIdentidad",
        label: "Nro. documento",
        type: "text",
        required: true,
        visibleInTable: true,
        placeholder: "Ingrese Nro. documento",
        validation: {
          dynamicDocumentFrom: "IdTipoDocIdentidad",
        },
      },
      {
        key: "Nombres",
        label: "Nombres",
        type: "text",
        required: true,
        visibleInTable: true,
      },
      {
        key: "Apellidos",
        label: "Apellidos",
        type: "text",
        required: true,
        visibleInTable: true,
      },
      {
        key: "Correo",
        label: "Correo",
        type: "email",
        visibleInTable: true,
      },
      {
        key: "Cargo",
        label: "Cargo",
        type: "lookup",
        required: true,
        visibleInTable: true,
        catalogoKey: "cargos",
      },
      {
        key: "TipoEntidad",
        label: "Tipo de entidad",
        type: "lookup",
        required: true,
        visibleInTable: true,
        catalogoKey: "tiposEntidad",
      },
      {
        key: "Activo",
        label: "Activo",
        type: "boolean",
        visibleInTable: true,
      },
    ],
  },

  personal: {
    key: "personal",
    titulo: "Personal PRONIED",
    descripcion: "Administración del personal PRONIED.",
    listaId: SHAREPOINT_CONFIG.lists.personal,
    titleField: "Nombres",
    fields: [
      {
        key: "IdTipoDocIdentidad",
        label: "Tipo de documento",
        type: "lookup",
        required: true,
        visibleInTable: true,
        catalogoKey: "tiposDocumento",
      },
      {
        key: "NroDocumentoIdentidad",
        label: "Nro. documento",
        type: "text",
        required: true,
        visibleInTable: true,
        placeholder: "Ingrese Nro. documento",
        validation: {
          dynamicDocumentFrom: "IdTipoDocIdentidad",
        },
      },
      {
        key: "Nombres",
        label: "Nombres",
        type: "text",
        required: true,
        visibleInTable: true,
      },
      {
        key: "Apellidos",
        label: "Apellidos",
        type: "text",
        required: true,
        visibleInTable: true,
      },
      {
        key: "IdUnidadZonal",
        label: "Unidad Zonal",
        type: "lookup",
        required: true,
        visibleInTable: true,
        catalogoKey: "unidadesZonales",
      },
      {
        key: "IdCargo",
        label: "Cargo",
        type: "lookup",
        required: true,
        visibleInTable: true,
        catalogoKey: "cargos",
      },
      {
        key: "IdModalidadContratacion",
        label: "Modalidad",
        type: "lookup",
        required: true,
        visibleInTable: true,
        catalogoKey: "modalidadContratacion",
      },
      {
        key: "MontoRemuneracion",
        label: "Remuneración",
        type: "number",
        required: true,
        visibleInTable: true,
        placeholder: "Ejemplo: 2500.00",
        validation: {
          decimal: true,
        },
      },
      {
        key: "CorreoInstitucional",
        label: "Correo Institucional",
        type: "email",
        visibleInTable: true,
        placeholder: "usuario@pronied.gob.pe",
        validation: {
          emailDomain: "@pronied.gob.pe",
        },
      },
      {
        key: "NroCelular",
        label: "Celular",
        type: "text",
        visibleInTable: true,
        placeholder: "987654321",
        validation: {
          onlyNumbers: true,
          startsWith: "9",
          minLength: 9,
          maxLength: 9,
        },
      },
      {
        key: "Activo",
        label: "Activo",
        type: "boolean",
        visibleInTable: true,
      },
    ],
  },
  
};